language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# sudo: false
before_script:
  - export PATH=$HOME/.local/bin:$PATH
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("WAHVectors"); Pkg.test("WAHVectors"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("WAHVectors")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("WAHVectors")); Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl"); include(joinpath("docs", "make.jl"))'
