# Project information
site_name: WAHVectors.jl
site_description: Word Aligned Hybrid compression of bit vectors.
site_author: The BioJulia Organisation
site_url: https://biojulia.github.io/WAHVectors.jl/

# Repository
repo_url: https://github.com/BioJulia/WAHVectors.jl

# Copyright
copyright: Copyright (c) 2016 The BioJulia Organisation

# Documentation and theme
theme: biojulia
docs_dir: 'build'

# Options
extra:
  logo:
  author:
    github: BioJulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite
  - def_list

# Page tree
pages:
- Home: index.md
- Manual:
  - Installation: man/install.md
- Contributing: man/contributing.md
